
analyzer:
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore ignore ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    
