
analyzer:
  errors:
    invalid_annotation_target: ignore
    
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
    unnecessary_null_comparison: ignore
include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    
